theme: jekyll-theme-cayman
title: [Dreamovies App Docs]
show_downloads: ["true"]
github:
  zip_url: https://github.com/DreaMovies/desktop-core/archive/dev_v1.zip
  tar_url: https://github.com/DreaMovies/desktop-core/archive/dev_v1.tar.gz
  exe_url: https://github.com/DreaMovies/desktop-core/archive/dev_v1.zip
  app_url: https://github.com/DreaMovies/desktop-core/archive/dev_v1.tar.gz
